jobs:
    build:
      working_directory: ~/build_only
      executor:
        name: node/default
        tag: '12.16'
      steps:
        - checkout
        - run: yarn install
        - run: yarn build
        - run: yarn test
        - store_test_results:
            path: ~/
version: 2.1
