orbs:
  node: circleci/node@1.1

jobs:
    build:
      working_directory: ~/build_only
      executor:
        name: node/default
        tag: '12.16'
      steps:
        - checkout
        - run: pwd
        - run: ls
        - store_artifacts:
            path: coverage
        - store_test_results:
            path: ~/
version: 2.1
