orbs:
  node: circleci/node@1.1

jobs:
    build:
      working_directory: ~/build_only
      executor:
        name: node/default
        tag: '12.16'
      steps:
        - checkout
        - run: yarn install
        - run: yarn lint
        - run: yarn build
        - run: cd packages/storefront-lwc && jest --collectCoverage=true
        - store_artifacts:
          path: coverage
        - run: yarn clean:stats
        - store_test_results:
            path: ~/
version: 2.1
