version: 2.1

orbs:
  node: circleci/node@1.1

jobs:
    build:
      working_directory: ~/build_only
      executor:
        name: node/default
        tag: '12.16'
      steps:
        - checkout
        - run: yarn install
        - run: yarn lint
        - run: yarn build
        - run: yarn test
        - run: cd packages/storefront-lwc && yarn test:badges
        - run: echo $CIRCLE_BRANCH
        - run: echo $CIRCLE_BUILD_NUM
        - store_artifacts:
            path: packages/storefront-lwc/coverage
            destination: $CIRCLE_BRANCH/jest-badges
        - run: yarn clean:stats
        - store_test_results:
            path: ~/
